### ISSUE TITLE
The Transient nightmare

### ISSUE THREAD

**Issue by SirHaesslich** [Kobting/STSFriendlyMinions#1]
I am not sure if it is intended or not, but when I summoned the minion during the Transient fight, it started partially tanking his atk debuffs. Insult to injury, the "will receive the lost attack at the end of the turn" effect was retained by the Transient regardless of who received the debuff, resulting in 100+ damage on not even the final attack.
Also, if it is not the fault of this mod, but rather the one that implemented the particular minion, I am sorry, I just saw the part about minions being able to be chosen for debuffs in the description.
The mod in question is The Mystic, the card Summon Fox.

**Comment by Kobting** [comment]
Fixed in 91b5ba5c430832124b77eeb4d440dc6c577c01ef
